# fly.toml app configuration file generated for gelbhart-dev
app = "gelbhart-dev"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:server"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "1"
  RAILS_SERVE_STATIC_FILES = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024